import sys
from cx_Freeze import setup, Executable

base = None
if sys.platform == "win32":
	base = "Win32GUI"

executableOptions = [
	Executable(
		"MPExpertAdjust.py",
		#icon="wp.ico",
		appendScriptToExe=True,
		appendScriptToLibrary=False,
		targetName="MPExpertAdjust.exe",
		base = base # <-- this is needed to hide Windows console
	)
]

buildOptions = dict(
	compressed=True,
	create_shared_zip = False,
	excludes = [],
	packages = [],
	include_files = [],
)

setup(
	name = "mpexpertadjust",
	version = '0.1',
	description = "Tool to adjust values generated by MPExpert",
	author = 'Matteo Mattei',
	author_email = 'matteo.mattei@gmail.com',
	options = dict(build_exe = buildOptions),
	executables = executableOptions
)